import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/app/src/theme/ThemeProvider';
import { ThemeSwitcher } from '@/app/src/theme/ThemeSwitcher';
import { ApolloClientWrapper } from '@/app/src/apollo/ApolloClientWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Developer Space',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const head = (
    <head>
      <title></title>
      <link
        rel="icon"
        href="https://img.freepik.com/premium-photo/african-woman-illustration-profile-african-colors-black-history-month-generative-ai_803320-854.jpg"
      />
    </head>
  );

  return (
    <html lang="en">
      {head}
      <body className={inter.className}>
        <ApolloClientWrapper>
          <ThemeProvider>
            <ThemeSwitcher />
            {children}
          </ThemeProvider>
        </ApolloClientWrapper>
      </body>
    </html>
  );
}
